name: party
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: null
  clip_shadow: ^0.2.1
  cloud_firestore: ^1.0.3
  email_validator: ^2.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  google_maps_flutter: ^2.0.2
  http: ^0.13.1
  image_picker: null
  intl: ^0.17.0
  location: ^4.1.1
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: null

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pattern.png
    - assets/icons/drinks.png
    - assets/icons/beer-hand.png
    - assets/icons/beer-mug.png
    - assets/icons/addUser-empty.png
    - assets/icons/addUser-filled.png
    - assets/icons/party-empty.png
    - assets/icons/party-filled.png
    - assets/icons/profile-empty.png
    - assets/icons/profile-filled.png
    - assets/icons/wall-empty.png
    - assets/icons/wall-filled.png
    - assets/icons/calendar.png
    - assets/icons/peopleComing.png
    - assets/icons/liver-empty.png
    - assets/icons/liver-filled.png
    - assets/icons/location.png
    - assets/icons/time.png
    - assets/icons/music.png
    - assets/icons/beer.png
    - assets/icons/toast.png
    - assets/icons/partyFriends.png
    - assets/icons/checkmark.png
    - assets/icons/removeUser-filled.png
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sylfaen
      fonts:
        - asset: assets/fonts/Sylfaen.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
